CREATE TABLE "GCG_4755_Current"(
 "ORDER_DATE" DATE,
 "ORDER_TIME" CHAR(40),
 "CUSTOMER_NAME" CHAR(30),
 "PO_NUMBER" CHAR(7),
 "PROD_TYPE" CHAR(15),
 "NOTES" CHAR(300),
 "CUSTOMER_CODE" CHAR(6),
 "ORDER_NUMBER" CHAR(7),
 "QUOTE_NUMBER" CHAR(7),
 "PERSON" CHAR(6),
 "CREATED" CHAR(45),
 "RECNUM" INTEGER,
 "PLANT" CHAR(50));

